branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
git:
  depth: false
matrix:
  include:
    - os: linux
      dist: bionic
      language: csharp
      mono: none
      dotnet: 2.2.105
      script: "./build.sh"
    - os: osx
      language: csharp
      mono: none
      dotnet: 2.2.107
      script: "./build.sh"
    - os: windows
      language: csharp
      mono: none
      before_script: dotnet --info
      script: "./build.cmd"
