version: '{build}'
environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
init:
- cmd: dotnet --info
- sh: dotnet --info
build_script:
- cmd: ./build.cmd
- sh: ./build.sh
test_script:
- chcp
- ps: dotnet run -c Release --no-build -p BullseyeSmokeTester
artifacts:
- path: ./**/*.nupkg
- path: BullseyeSmokeTester 
deploy: off
